# Generated by Django 5.1.7 on 2025-04-10 06:06

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
    ]
